### ISSUE TITLE
cannot validate secret key

### ISSUE THREAD

**Issue by its2fun** [hps/heartland-gravity-forms-addon#3] opened 2015-04-08 18:45 UTC
I am trying to set up the gravity forms add-on and I am receiving this error for secret key:
Error validating this key. Please try again later.

I have tried both the certification pair and the production pair.

Please advise, thanks!

**Comment by slogsdon** [comment] 2015-04-08 20:37
@its2fun I have a feeling this is related to your other open issue (#4). While I'm fixing that issue, I'll check to see if I can replicate this issue on my local installation.

**Comment by slogsdon** [comment] 2015-04-16 16:24
@its2fun We just merge in the fix for this. Would you mind checking it out and seeing if it resolves your issue?

**Comment by its2fun** [comment] 2015-04-16 21:29
I logged into my wp admin and deactivated and deleted the previous plugin. I downloaded the updated zip file here then activated it, however the problem persists. Is the process I followed correct?

**Comment by slogsdon** [comment] 2015-04-17 13:52
Is your other issue resolved? If so, this one is probably caused by mismatched public and secret API keys or perhaps some whitespace that was copied with the actual keys.

**Comment by its2fun** [comment] 2015-04-17 14:31
The other issue is resolved. This one however, is not resolved. I went to the HPS developer portal and used the copy to clipboard function and also tried manually copying the production keys, but I am still receiving the error .

**Comment by slogsdon** [comment] 2015-04-17 17:05
Does the spinner remain there, or do you get the red 'x'? If it keeps spinning, there's usually an error or exception being thrown in the backend when that happens, and you can typically see the error in your logs or in the Network panel of your browser's developer tools when the request to `/wp-admin/admin-ajax.php`.

**Comment by its2fun** [comment] 2015-04-17 17:43
The spinner spins briefly and then is replaced with the error message: Error validating this key. Please try again later.
I do not get a red X. I can do a screen share if that helps

**Comment by slogsdon** [comment] 2015-04-20 14:08
@its2fun That usually happens when there's an error or exception being thrown in the backend. You can typically see the error in your logs or in the Network panel of your browser's developer tools when the request to `/wp-admin/admin-ajax.php`. Do you have any kind of PHP error on your end?

**Comment by its2fun** [comment] 2015-04-24 19:30
Not that I can see.

​

**Comment by its2fun** [comment] 2015-04-29 11:25
Hi! When I replied via email I attached a screen grab. Did you receive it? Thanks!

**Comment by slogsdon** [comment] 2015-04-29 17:46
@its2fun I did not. Would you email that over to EntApp_DevPortal@e-hps.com? I should be able to get it there.

**Comment by slogsdon** [comment] 2015-05-04 20:27
@its2fun Do you know what version of PHP and Wordpress you are running? I want to try to duplicate your environment to see if I can replicate your issue. We haven't run into anything similar to your issue with this add on before, and I want to make sure you can process with us using Gravity Forms.

**Comment by its2fun** [comment] 2015-05-05 14:47
Aha!  I found the issue.

I had the WP SecureSubmit plugin installed because I tried using that
before I found the gravity forms.  When I deactivated that plugin, the
problem resolved.

Sorry for the inconvenience and thank you so much for all of your efforts!!!

Patti

**Comment by slogsdon** [comment] 2015-05-05 14:50
Great news!

I'll be sure to update both to remove any incompatibilities as soon as
possible. We're also working a new version of our PHP SDK that will
eventually be bundled with all of our WP plugins.

**Closed as completed** 2015-10-15 17:53 UTC
